triggers:
- description: null
  envs: []
  last_enabled_at: 2024-06-17 13:46:56.652772
  name: no_od_nov
  pipeline_uuid: no_to_od_nov_2023
  schedule_interval: null
  schedule_type: api
  settings: null
  sla: null
  start_time: 2024-06-17 13:46:00
  status: active
  token: 3b1fa8c6d5754730a48c688d11446958
  variables: {}
